-- Actividad Oracle 11g - Esquema HR

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME IN ('EMPLOYEES','DEPARTMENTS');

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMPLOYEES','DEPARTMENTS');

ALTER TABLE EMPLOYEES DISABLE CONSTRAINT EMP_EMP_ID_PK;
ALTER TABLE EMPLOYEES DISABLE CONSTRAINT EMP_DEPT_FK;
ALTER TABLE DEPARTMENTS DISABLE CONSTRAINT DEPT_ID_PK;

INSERT INTO DEPARTMENTS VALUES (10,'PRUEBA1',NULL,1700);
INSERT INTO DEPARTMENTS VALUES (10,'PRUEBA2',NULL,1700);

INSERT INTO EMPLOYEES
(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID)
VALUES
(999,'JUAN','PEREZ','JPEREZ','515123456',SYSDATE,'IT_PROG',3000,NULL,100,9999);

ALTER TABLE DEPARTMENTS ENABLE CONSTRAINT DEPT_ID_PK;
ALTER TABLE EMPLOYEES ENABLE CONSTRAINT EMP_EMP_ID_PK;
ALTER TABLE EMPLOYEES ENABLE CONSTRAINT EMP_DEPT_FK;

CREATE TABLE DEPARTMENTS2 AS
SELECT * FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS2 VALUES (300,'SISTEMAS',100,1700);
INSERT INTO DEPARTMENTS2 VALUES (301,'INFRAESTRUCTURA',100,1700);
INSERT INTO DEPARTMENTS2 VALUES (302,'DESARROLLO',100,1700);

SELECT * FROM DEPARTMENTS2;

DECLARE
BEGIN
   DBMS_OUTPUT.PUT_LINE('Inicio de la transacción');
   INSERT INTO DEPARTMENTS2 VALUES (400,'PRUEBA_TRANS',100,1700);
   DBMS_OUTPUT.PUT_LINE('Fin de la transacción');
   COMMIT;
END;
/

ROLLBACK;

SELECT LOG_MODE FROM V$DATABASE;
